import type { DataSourceManifest, NormalizedAsset, NormalizedProduct, SeedDataSource } from "../types.js";
import { hydrateAssets, hydrateProducts } from "../static-source.js";
// Generated by `pnpm --filter @workspace/api-server run import:cytek` — do not edit by hand.
import manifest from "./manifest.json";
import assets from "./assets.json";
import products from "./products.json";

/**
 * The Cytek data shipped with the application. It is saved into the data
 * source store the first time the server runs (see DataSourceService) so it
 * behaves exactly like an uploaded source afterwards.
 */
export const cytekSeed: SeedDataSource = {
  id: (manifest as DataSourceManifest).id,
  name: (manifest as DataSourceManifest).name,
  manifest: manifest as DataSourceManifest,
  assets: hydrateAssets(assets) as NormalizedAsset[],
  products: hydrateProducts(products) as NormalizedProduct[],
};
