import type { DataSourceManifest } from "../types.js";
import { createStaticDataSource } from "../static-source.js";
// Generated by `pnpm --filter @workspace/api-server run import:cytek` — do not edit by hand.
import manifest from "./manifest.json";
import assets from "./assets.json";
import products from "./products.json";

export const cytekDataSource = createStaticDataSource({
  manifest: manifest as DataSourceManifest,
  assets,
  products,
});
