import type {
  AssetLookupResult,
  DataSource,
  DataSourceManifest,
  NormalizedAsset,
  NormalizedProduct,
} from "./types.js";

/** Normalizes a serial for matching: trim + lowercase. */
export function normalizeSerial(serial: string): string {
  return serial.trim().toLowerCase();
}

/**
 * Contract status shown in the UI, derived from the contract end date so it
 * stays correct as time passes. Wording matches what the previous dataset
 * displayed ("Activated" / "Expired").
 */
export function deriveContractStatus(contractEndDate: string, now: Date = new Date()): string {
  if (!contractEndDate) return "";
  const end = new Date(`${contractEndDate}T23:59:59Z`);
  if (Number.isNaN(end.getTime())) return "";
  return end.getTime() >= now.getTime() ? "Activated" : "Expired";
}

const ASSET_DEFAULTS: NormalizedAsset = {
  serialNumber: "", assetName: "", accountName: "", facilityName: "", serviceTerritory: "",
  primaryTechnician: "", contractNumber: "", contractType: "", contractEndDate: "", productName: "",
  contactName: "", contactEmail: "", street: "", city: "", stateZip: "", region: "", country: "",
  assetStatus: "", installDate: "",
};

const PRODUCT_DEFAULTS: NormalizedProduct = {
  partName: "", partNumber: "", listPrice: 0, netPrice: 0, category: "Parts", unit: "",
};

/**
 * The generated JSON omits empty-string fields to stay small; restore them so
 * every record has the full normalized shape.
 */
function hydrate<T extends object>(value: unknown, defaults: T, what: string): T[] {
  if (!Array.isArray(value)) {
    throw new Error(`Data source ${what} is not an array — was the import run?`);
  }
  return value.map((r) => ({ ...defaults, ...(r as Partial<T>) }));
}

/**
 * An in-memory DataSource built from already-normalized records (today these
 * are JSON files generated by the importer and bundled with the server).
 * Indexes serials once; lookups are O(1).
 */
export function createStaticDataSource(input: {
  manifest: DataSourceManifest;
  assets: unknown;
  products: unknown;
}): DataSource {
  const manifest = input.manifest;
  const assets = hydrate(input.assets, ASSET_DEFAULTS, `${manifest.id} assets`);
  const products = hydrate(input.products, PRODUCT_DEFAULTS, `${manifest.id} products`);

  const bySerial = new Map<string, NormalizedAsset>();
  for (const a of assets) {
    const key = normalizeSerial(a.serialNumber);
    if (key && !bySerial.has(key)) bySerial.set(key, a);
  }
  const serials = [...bySerial.values()].map((a) => a.serialNumber).sort();
  const services = products.filter((p) => p.category === "Service");

  return {
    id: manifest.id,
    name: manifest.name,
    manifest,
    listSerials: () => serials,
    lookupAsset: (serial: string): AssetLookupResult | null => {
      const found = bySerial.get(normalizeSerial(serial));
      if (!found) return null;
      return { ...found, contractStatus: deriveContractStatus(found.contractEndDate) };
    },
    listProducts: () => products,
    listServices: () => services,
  };
}
